### ISSUE TITLE
Crawler does not seem to follow the links

### ISSUE THREAD

**Issue by SolSearch** [Norconex/collector-http#506]
Hello,

I am seeing a strange behavior where my main page is being crawled but the crawler is not following the links.  I don't get any errors but the crawler stops after crawling the main page.  I have played with the maxDepth setting but of no avail   Are there any configuration settings that I could use to force the crawler to follow the links in such cases?

Thank You, 

[config.txt](https://github.com/Norconex/collector-http/files/2215178/config.txt)

**Comment by joettt** [comment]
The main page has robots set to noindex but does not have noFollow parameter.  Besides, in the attached configuration file I have set it to <robotsMeta ignore="true" />.

**Comment by joettt** [comment]
The site is password protected, the crawler account is authenticated on a different domain (stayOnDomain="false").   Also, to handle the redirects, I have added:               <validStatusCodes>200,302</validStatusCodes>                 
I have not attached the main page since it contains users specific information.  If needed, I can clean it up and attach to the case.

Thank You.

**Comment by essiembre** [comment]
I presume it is a cut-n-paste error, but you have a few unclosed tags in your attached config.  Once I fixed those, I ran your config and got 39 documents processed properly.   Which URL does not have its links followed from the ones in your attached config?  

You can try to change the log level (log4j.properties file) to DEBUG for more information and see if you can find anything helpful in the logs.

Also, I noticed you have ``<maxRedirects>0</maxRedirects>`` which disables redirect.  Have you tried setting a higher number?

I am not sure if your problem is authentication-related, but I observed you have the ``<authURL``> set to https://gccollab.ca/ whereas I think it should probably be  https://account.gccollab.ca/login/

**Comment by joettt** [comment]
I also get 39 documents.  The https://gccollab.ca/members  page has links to the https://gccollab.ca/profile folder the crawler is not following.   I have changed the log level to DEBUG but I don't see anything more useful.  I have tried increasing maxRedirects and have changed the authURL to  https://account.gccollab.ca/login/ but still the same issue.

**Comment by essiembre** [comment]
Trying with the DEBUG log level myself, I get the cause for the failure.  Look for a log line that has: ``DEBUG - Authentication response:``

The "form" method is for generic form authentication that does not rely on an enhanced security mechanism such as generated tokens.  The site you want to crawl uses dynamically generated CSRF tokens combined with cookies/redirects to authenticate.  

For this, you would need a custom authentication solution, that would extract the generated token and submit it back properly unless you are aware of another way to authenticate for this site.  You can create your own HttpClient factory that does that. It is probably easier to subclass ``GenericHttpClientFactory`` and override the ``authenticateUsingForm(HttpClient httpClient)`` method.

If you know the site owner, maybe they can relax authentication for specific IPs or User Agent.

**Comment by joettt** [comment]
We are going to relax authentication for the User Agent.  Thank you very much for your input.

**Comment by essiembre** [comment]
Glad you found a solution.  If you can confirm the GC Collab authentication method to be a standard or commonly used one, we can create a new feature request to have it supported natively by the HTTP Collector.  Let me know.
